{
 "title": "Cloud Price Tracker",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Average GB/mo Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg(cloud_vm_cost_per_gb_hour) by (provider, region) * 24 * 30",
     "legendFormat": "{{provider}} ({{region}})"
    }
   ]
  },
  {
   "title": "Average vCPU/mo Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg(cloud_vm_cost_per_vcpu_hour) by (provider, region) * 24 * 30",
     "legendFormat": "{{provider}} ({{region}})"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "RAM Price per GB/mo",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(cloud_vm_cost_per_gb_hour) by (instance_type, region, provider) * 24 * 30",
     "legendFormat": "{{provider}} {{region}} {{instance_type}}"
    }
   ]
  },
  {
   "title": "Compute Price per vCPU/mo",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(cloud_vm_cost_per_vcpu_hour) by (instance_type, region, provider) * 24 * 30",
     "legendFormat": "{{provider}} {{region}} {{instance_type}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{container_name=\"cloud-pricing-monitor-cloud-pricing-monitor-1\"} |= `` | json | line_format `{{.msg}} {{.err}} {{.error}}`"
      }
     ]
    }
   ]
  }
 ]
}